version: '3'
services:
  loki:
    image: grafana/loki:2.8.0
    container_name: 'loki'
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - contract-network 
  
  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana'
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: true
        - name: Tempo
          type: tempo
          access: proxy
          orgId: 1
          url: http://tempo:3200
          basicAuth: false
          isDefault: false
          version: 1
          editable: true
          apiVersion: 1
        EOF
        /run.sh
    ports:
      - "3000:3000"
    networks:
      - contract-network
        
  tempo:
    image: grafana/tempo:latest
    container_name: 'tempo'
    # command: [ "-config.file=/etc/tempo.yaml" ]
    # volumes:
    #   - ./grafana-components/tempo.yaml:/etc/tempo.yaml
    #   - ./grafana-components/tempo-data/:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "9411" # zipkin
      - "4317:4317" # grpc
    networks:
      - contract-network
  
networks:
  contract-network:
