version: '3'
services:
  redis:
    image: docker.io/bitnami/redis:7.0
    container_name: 'redis'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6380:6379"
    networks:
      - contract-network