apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redismessagebus
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: "host.docker.internal:6379"
  - name: redisPassword
    value: ""
  - name: consumerID
    value: "myGroup"
  - name: enableTLS
    value: "false"