apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis.statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: "host.docker.internal:6379"
  - name: redisPassword
    value: ""
  - name: enableTLS
    value: "false"